### PR TITLE
Wordpress stack : share TZ with containers and NGINX tweak for fail2ban integration

### PR DESCRIPTION
**Pull request by t3cneo**
Hi

Thanks for sharing your stack, it became mine at first run!!

I always set fail2ban jails for my docker stack as soon as their is a public login form, those few extra lines made it possible because as you must know fail2ban parse logs based on fail regex, IP and time

I thought this PR wouldn't break any already running stack and could only make it safer for paranoid people like me

### CODE REVIEW

**Comment by julienhmmt** [comment]
Hello !
Excellent, glad to hear this =)
To be honest, I was a bit confused because I couldn't see real IPs... And now, it works. Super ;) Let's merge it !

**Comment by julienhmmt** [comment]
miss play with GitHub... sorry. Merged.

**Comment by t3cneo** [comment]
Same code could be applied to your other NGINX stack for the same effect/reason

**Comment by julienhmmt** [comment]
added in other conf, thank you very much ! =)

**Pull request merged**
